# Generated by Django 5.2.1 on 2025-05-20 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historial_riego',
            old_name='cantidad_de_agua',
            new_name='cantidad_agua',
        ),
    ]
