# Generated by Django 5.2.1 on 2025-05-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_alter_usuario_correo_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('operario', 'Operario')], default='operario', max_length=20),
        ),
    ]
