# Generated by Django 5.2.1 on 2025-05-22 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_alter_usuario_rol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracion_riego',
            old_name='tipo_de_riego',
            new_name='tipo_riego',
        ),
    ]
