# Generated by Django 5.2.1 on 2025-05-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_rename_cantidad_de_agua_historial_riego_cantidad_agua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('empleado', 'Empleado')], default='cliente', max_length=20),
        ),
    ]
