# Generated by Django 5.2.1 on 2025-06-02 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_rename_tipo_de_riego_configuracion_riego_tipo_riego'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
