# Generated by Django 5.2.1 on 2025-06-02 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_delete_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='historial_riego',
        ),
        migrations.DeleteModel(
            name='mantenimiento',
        ),
    ]
