# Generated by Django 5.2.1 on 2025-06-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_delete_historial_riego_delete_mantenimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectura_sensor',
            name='unidad',
            field=models.CharField(choices=[('porcentaje', 'Porcentaje'), ('grados', 'Grados')], default='porcentaje', max_length=10),
        ),
        migrations.AlterField(
            model_name='lectura_sensor',
            name='fecha_hora',
            field=models.DateTimeField(),
        ),
    ]
